name: Run tests

on:
  push:
    branches:
    - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main
  
    # Install python
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    # Install requirements
    - name: Install pip requirements
      run: |
        pip install -r ./main/project/requirements.txt

    # Run tests
    - name: Run tests
      run: |
        ./main/project/tests.sh